from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


RUNTIME_SCHEMA = "chartpilot.runtime/v1"
LICENSE_SCHEMA = "chartpilot.third-party-licenses/v1"
LOCK_HEADER = (
    "# Generated by scripts/runtime/update-lock.ps1 for CPython 3.13 Windows x64.\n"
    "# Regenerate deliberately; do not edit package hashes by hand.\n"
)


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json_atomic(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def parse_wheel(path: Path) -> dict[str, Any]:
    if path.suffix.lower() != ".whl":
        raise ValueError(f"Source distributions are not allowed: {path.name}")
    parts = path.stem.split("-")
    if len(parts) < 5:
        raise ValueError(f"Invalid wheel filename: {path.name}")
    name = canonical_name(parts[0])
    version = parts[1]
    python_tag, abi_tag, platform_tag = parts[-3:]
    platforms = set(platform_tag.split("."))
    if not platforms.issubset({"any", "win_amd64"}):
        raise ValueError(f"Wheel is not Windows x64 compatible: {path.name}")
    if "cp313t" in python_tag or "cp313t" in abi_tag:
        raise ValueError(f"Free-threaded wheel is not allowed: {path.name}")
    return {
        "name": name,
        "version": version,
        "filename": path.name,
        "sha256": sha256_file(path),
        "size_bytes": path.stat().st_size,
        "python_tag": python_tag,
        "abi_tag": abi_tag,
        "platform_tag": platform_tag,
    }


def direct_requirements(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.fullmatch(r"([A-Za-z0-9_.-]+)==([^\s;]+)", line)
        if not match:
            raise ValueError(f"Direct dependency must use an exact version pin: {line}")
        values[canonical_name(match.group(1))] = match.group(2)
    if not values:
        raise ValueError("No direct dependencies were found.")
    return values


def wheel_records(wheelhouse: Path) -> list[dict[str, Any]]:
    paths = sorted(wheelhouse.iterdir(), key=lambda item: item.name.lower())
    if not paths:
        raise ValueError(f"Wheelhouse is empty: {wheelhouse}")
    records = [parse_wheel(path) for path in paths if path.is_file()]
    names = [record["name"] for record in records]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise ValueError(f"Multiple wheels found for: {', '.join(duplicates)}")
    return sorted(records, key=lambda item: (item["name"], item["version"]))


def command_lock_wheels(args: argparse.Namespace) -> int:
    wheelhouse = Path(args.wheelhouse).resolve(strict=True)
    requirements = Path(args.requirements).resolve(strict=True)
    output = Path(args.output).resolve()
    direct = direct_requirements(requirements)
    records = wheel_records(wheelhouse)
    available = {record["name"]: record for record in records}
    missing = sorted(set(direct) - set(available))
    if missing:
        raise ValueError(f"Direct dependencies missing from wheelhouse: {', '.join(missing)}")
    mismatched = [
        name
        for name, version in direct.items()
        if available[name]["version"] != version
    ]
    if mismatched:
        raise ValueError(f"Direct dependency versions do not match: {', '.join(mismatched)}")
    lines = [LOCK_HEADER.rstrip("\n")]
    lines.extend(
        f"{record['name']}=={record['version']} --hash=sha256:{record['sha256']}"
        for record in records
    )
    write_text_atomic(output, "\n".join(lines) + "\n")
    print(json.dumps({"ok": True, "packages": len(records), "output": str(output)}))
    return 0


def metadata_values(metadata: importlib.metadata.PackageMetadata, key: str) -> list[str]:
    values = metadata.get_all(key) or []
    return sorted({value.strip() for value in values if value and value.strip()})


def license_files(distribution: importlib.metadata.Distribution) -> list[str]:
    matches: list[str] = []
    for item in distribution.files or []:
        name = Path(str(item)).name.upper()
        if name.startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE")):
            matches.append(str(item).replace("\\", "/"))
    return sorted(set(matches))


def installed_distributions() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    packages: list[dict[str, Any]] = []
    licenses: list[dict[str, Any]] = []
    for distribution in importlib.metadata.distributions():
        metadata = distribution.metadata
        raw_name = metadata.get("Name") or "unknown"
        name = canonical_name(raw_name)
        version = distribution.version
        packages.append({"name": name, "version": version})
        license_expression = (metadata.get("License-Expression") or "").strip()
        license_value = (metadata.get("License") or "").strip()
        classifiers = [
            value for value in metadata_values(metadata, "Classifier")
            if value.startswith("License ::")
        ]
        project_urls = metadata_values(metadata, "Project-URL")
        homepage = (metadata.get("Home-page") or "").strip()
        licenses.append(
            {
                "name": name,
                "version": version,
                "license_expression": license_expression or None,
                "license": license_value or "unknown",
                "license_classifiers": classifiers,
                "homepage": homepage or None,
                "project_urls": project_urls,
                "license_files": license_files(distribution),
            }
        )
    packages.sort(key=lambda item: (item["name"], item["version"]))
    licenses.sort(key=lambda item: (item["name"], item["version"]))
    return packages, licenses


def command_runtime_manifest(args: argparse.Namespace) -> int:
    runtime_lock_path = Path(args.runtime_lock).resolve(strict=True)
    dependency_lock_path = Path(args.dependency_lock).resolve(strict=True)
    wheelhouse = Path(args.wheelhouse).resolve(strict=True)
    output = Path(args.output).resolve()
    licenses_output = Path(args.licenses_output).resolve()
    runtime_lock = load_json(runtime_lock_path)
    if runtime_lock.get("schema_version") != "chartpilot.runtime-lock/v1":
        raise ValueError("Unsupported runtime lock schema.")
    wheels = wheel_records(wheelhouse)
    packages, licenses = installed_distributions()
    python_config = runtime_lock["python"]
    manifest = {
        "schema_version": RUNTIME_SCHEMA,
        "runtime_id": runtime_lock["runtime_id"],
        "status": "ready",
        "upstream": runtime_lock["upstream"],
        "python": {
            "implementation": platform.python_implementation(),
            "version": platform.python_version(),
            "architecture": platform.architecture()[0],
            "interpreter": python_config["interpreter"],
        },
        "dependency_lock": {
            "path": dependency_lock_path.name,
            "sha256": sha256_file(dependency_lock_path),
        },
        "wheels": wheels,
        "installed_distributions": packages,
        "environment": runtime_lock["environment"],
        "health": {"status": "pending", "checks": []},
        "builder": {
            "script_version": "1.0.0",
            "built_at_utc": datetime.now(timezone.utc).isoformat(),
        },
    }
    license_manifest = {
        "schema_version": LICENSE_SCHEMA,
        "status": "complete",
        "distributions": licenses,
    }
    write_json_atomic(output, manifest)
    write_json_atomic(licenses_output, license_manifest)
    print(
        json.dumps(
            {
                "ok": True,
                "manifest": str(output),
                "licenses": str(licenses_output),
                "packages": len(packages),
            }
        )
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    lock_parser = subparsers.add_parser("lock-wheels")
    lock_parser.add_argument("--wheelhouse", required=True)
    lock_parser.add_argument("--requirements", required=True)
    lock_parser.add_argument("--output", required=True)
    lock_parser.set_defaults(handler=command_lock_wheels)

    manifest_parser = subparsers.add_parser("runtime-manifest")
    manifest_parser.add_argument("--runtime-lock", required=True)
    manifest_parser.add_argument("--dependency-lock", required=True)
    manifest_parser.add_argument("--wheelhouse", required=True)
    manifest_parser.add_argument("--output", required=True)
    manifest_parser.add_argument("--licenses-output", required=True)
    manifest_parser.set_defaults(handler=command_runtime_manifest)
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.handler(args))
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(
            json.dumps(
                {
                    "ok": False,
                    "error": {
                        "code": "RUNTIME_METADATA_ERROR",
                        "message": str(exc),
                        "exception_type": type(exc).__name__,
                    },
                }
            ),
            file=sys.stderr,
        )
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
